// <auto-generated />
namespace ERP_Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class address_changes_21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(address_changes_21));
        
        string IMigrationMetadata.Id
        {
            get { return "201611231619257_address_changes_21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
