// <auto-generated />
namespace ERP_Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class stock_transaction_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stock_transaction_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201701201547023_stock_transaction_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
